# Generated by Django 4.0.2 on 2022-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_comments_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Browser_type', models.CharField(max_length=100)),
                ('Ip', models.IntegerField(max_length=20)),
                ('Browser_version', models.CharField(max_length=100)),
                ('OS_type', models.CharField(max_length=100)),
                ('Os_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(null=True, verbose_name='%d/%m/%d'),
        ),
    ]
