# Generated by Django 4.0.2 on 2022-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_visitors_alter_comments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='Ip',
            field=models.IntegerField(),
        ),
    ]
