# Generated by Django 4.0.2 on 2022-07-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_visitors_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
